import { defineConfig } from 'weapp-vite/config'
import { UnifiedViteWeappTailwindcssPlugin } from 'weapp-tailwindcss/vite'
// const { UnifiedViteWeappTailwindcssPlugin } = await import('weapp-tailwindcss/vite')
// const { UnifiedViteWeappTailwindcssPlugin } = require('weapp-tailwindcss/vite')
// import { TailwindcssPatcher } from 'tailwindcss-patch'

// const twPatcher = new TailwindcssPatcher(/* options */)
// do patch
// twPatcher.patch()
// // get all contexts at runtime
// twPatcher.getContexts()
// // get all class generated by tailwindcss utilities
// twPatcher.getClassSet()

export default defineConfig({
  weapp: {
    // weapp-vite options
  },
  plugins: [
    UnifiedViteWeappTailwindcssPlugin({
      rem2rpx: true
    }),
    // {
    //   name: 'xxx',
    //   enforce: 'post',
    //   generateBundle: {
    //     handler(options, bundle, isWrite) {
    //       const set = twPatcher.getClassSet()
    //       console.log(set)
    //     },
    //   },
    // }
  ]
})
